In [ ]:
import torch

#Scalar
tensor = torch.tensor(7)
#tensor

tensor.ndim
tensor.item()

7

In [ ]:
#VectorS
vector = torch.tensor([7,7])
vector
#vector.size()
# vector.shape
vector.ndim

1

In [ ]:
# MATRIXES

MATRIX = torch.tensor([[1,2],
                 [3,4]])
# MATRIX
# MATRIX[0]
MATRIX.ndim
MATRIX.shape
MATRIX.size()

torch.Size([2, 2])

In [ ]:
# TENSORS

TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
# TENSOR
TENSOR.ndim
# TENSOR.shape,TENSOR[0, 2, 2],TENSOR[0, 1, 1]

3

In [ ]:
TENSOR_2 = torch.tensor([[[1,2,3],
                          [3,2,1]],
                         [[4,5,6],
                          [6,7,8]]])
# TENSOR_2.ndim
TENSOR_2.shape

torch.Size([2, 2, 3])

In [ ]:
# Random Tensors
random_tensor = torch.rand(2,2,3)
random_tensor

tensor([[[0.6115, 0.4853, 0.6747],
         [0.3081, 0.7350, 0.5895]],

        [[0.2102, 0.6733, 0.5444],
         [0.9846, 0.2461, 0.5339]]])

In [ ]:
random_image_size_tensor = torch.rand(224, 224, 3)
random_image_size_tensor

tensor([[[0.3187, 0.7515, 0.4169],
         [0.4987, 0.3760, 0.3552],
         [0.7044, 0.4367, 0.3440],
         ...,
         [0.2761, 0.4252, 0.6645],
         [0.6928, 0.2800, 0.5687],
         [0.1922, 0.1290, 0.7906]],

        [[0.8949, 0.7134, 0.2494],
         [0.8824, 0.3464, 0.0143],
         [0.3853, 0.4617, 0.3227],
         ...,
         [0.2354, 0.7449, 0.2040],
         [0.8478, 0.0252, 0.3214],
         [0.7619, 0.4181, 0.8927]],

        [[0.1259, 0.5917, 0.9133],
         [0.6736, 0.4638, 0.0473],
         [0.0699, 0.4755, 0.0829],
         ...,
         [0.4829, 0.2807, 0.5539],
         [0.3243, 0.2001, 0.4312],
         [0.6970, 0.0747, 0.1987]],

        ...,

        [[0.3884, 0.1923, 0.1062],
         [0.7095, 0.9751, 0.7010],
         [0.4803, 0.8952, 0.9559],
         ...,
         [0.9081, 0.6960, 0.7411],
         [0.5636, 0.4537, 0.8248],
         [0.3893, 0.3476, 0.9247]],

        [[0.8607, 0.1333, 0.0463],
         [0.2339, 0.8737, 0.9294],
         [0.

In [ ]:
#Multiplying tensors


In [ ]:
# Zero and one tensors
zeros = torch.zeros(5,5)
ones = torch.ones(5,5, dtype=torch.int)

zeros, ones

(tensor([[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]),
 tensor([[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]], dtype=torch.int32))

In [ ]:
# Using torch.arange
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
# Creating tensors-like

ten_zeros = torch.ones_like(input=one_to_ten)
ten_zeros

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [22]:
import torch
#Setting the tensor details
int_64_tensor = torch.tensor([3,4,5],
                               			dtype=None,
                               device=None,
                               requires_grad=False)
int_64_tensor, int_64_tensor.dtype

(tensor([3, 4, 5]), torch.int64)

In [23]:
#Changing the tensor`s datatype
float_32_tensor = int_64_tensor.type(torch.float32)
float_32_tensor, float_32_tensor.dtype


(tensor([3., 4., 5.]), torch.float32)

In [24]:
#Manipulating tensors
tensor = torch.tensor([1,2,3])
#tensor+10,tensor*10

#PyTorch inbuilt functions
torch.mul(tensor, 10), torch.add(tensor, 10)

(tensor([10, 20, 30]), tensor([11, 12, 13]))

In [25]:
#Matrix multiplication
print(tensor*tensor)
print(f"equals {tensor*tensor}")

torch.matmul(tensor, tensor)

torch.matmul(torch.rand(3,3), torch.rand(3,3))

tensor([1, 4, 9])
equals tensor([1, 4, 9])


tensor([[0.2727, 0.9520, 0.4123],
        [0.7964, 1.8842, 1.2829],
        [0.4529, 0.6233, 0.4323]])

In [26]:
tensor_B = torch.rand(3,2)
tensor_B.shape, tensor_B.T.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [27]:
# Tensor Aggregation

x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [28]:
#Finding the max
torch.min(x), x.min()

#Finding tge max
torch.max(x), x.max()

#SUM
x.sum()

#Max and min oosotion
x.argmin()
x.argmax()
x[x.argmax()]



tensor(90)

In [29]:
#Manipulating the tensor's shape

x = torch.arange(1., 10.)

x_reshaped = x.reshape(1,3,1,1,3)
x.shape, x_reshaped.shape

torch.stack([x,x,x], dim=0), torch.stack([x,x,x], dim=1)

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([[1., 1., 1.],
         [2., 2., 2.],
         [3., 3., 3.],
         [4., 4., 4.],
         [5., 5., 5.],
         [6., 6., 6.],
         [7., 7., 7.],
         [8., 8., 8.],
         [9., 9., 9.]]))

In [36]:
x_reshaped,x_reshaped.shape

(tensor([[[[[1., 2., 3.]]],
 
 
          [[[4., 5., 6.]]],
 
 
          [[[7., 8., 9.]]]]]),
 torch.Size([1, 3, 1, 1, 3]))

In [38]:
x_squeezed = x_reshaped.squeeze()
x_squeezed,x_squeezed.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [43]:
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
x_unsqueezed

tensor([[[1., 2., 3.]],

        [[4., 5., 6.]],

        [[7., 8., 9.]]])

In [47]:
# torch.permute

x = torch.rand(size=(224,224,3)) #[height, width, color_channels]
x.shape

x_permuted = x.permute(2,0,1)
# x_permuted.shape

tensor([[[0.8847, 0.4900, 0.4233],
         [0.4323, 0.0819, 0.7636],
         [0.6431, 0.3759, 0.6809],
         ...,
         [0.8019, 0.9226, 0.6821],
         [0.1789, 0.1783, 0.1223],
         [0.8686, 0.7684, 0.8544]],

        [[0.2396, 0.6415, 0.4570],
         [0.8649, 0.9245, 0.2369],
         [0.1114, 0.0426, 0.1654],
         ...,
         [0.6330, 0.9539, 0.8315],
         [0.1431, 0.8489, 0.7550],
         [0.0395, 0.7144, 0.7035]],

        [[0.7594, 0.0963, 0.6328],
         [0.4382, 0.8998, 0.8110],
         [0.7472, 0.5562, 0.7891],
         ...,
         [0.5574, 0.2504, 0.9483],
         [0.5080, 0.7867, 0.8172],
         [0.1688, 0.0944, 0.8479]],

        ...,

        [[0.2526, 0.9388, 0.4973],
         [0.4705, 0.4431, 0.4670],
         [0.2322, 0.2195, 0.9620],
         ...,
         [0.1684, 0.7649, 0.7558],
         [0.5728, 0.3694, 0.0955],
         [0.2236, 0.7852, 0.6363]],

        [[0.3170, 0.2741, 0.3089],
         [0.4361, 0.0280, 0.8225],
         [0.

In [52]:
# Indexing (selecting data from tensors)

x = torch.arange(1, 10).reshape(1,3,3)
# x,x.shape
x[0][0][2], x[0, 0, 2]

(tensor(3), tensor(3))

In [57]:
x[:,1,:]
x[:,1,1]

tensor([5])

In [59]:
#  PyTorch and NumPy
import torch
import numpy as np


array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array).type(torch.int64)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1, 2, 3, 4, 5, 6, 7]))